Use pdr sapphire wrapper for making transactions
oceanprotocol/pdr-utils pull request #16
Opened 2023-07-28 12:44 UTC by trizin

Fixes #15

Changes proposed in this PR:

- Use pdr sapphire wrapper for making transactions

2023-07-30 06:35 UTC, alexcos20 requested changes
This will break all the existing flows, especially barge.

Proposal:
 - have a function called is_sapphire_rpc  (takes web3, returns true if chain_id is a match)
 - when needed in functions that require privacy, create the tx using encodeABI.
 - then check if is_sapphire_rpc  
 - if yes:  call wrapper.send_encrypted_sapphire_tx
 - else, sign the tx and use web3.py to send the transaction
 - keep wait_for_receipt check at the end

2023-07-31 09:34 UTC, trizin commented
Right, I haven't thought about the impacts on local deployment. I'll update the PR, thank you! @alexcos20

2023-08-01 10:17 UTC, alexcos20 requested changes

2023-08-01 10:17 UTC, alexcos20 commented on pdr_utils/contract.py
> +            if is_sapphire_rpc(self.config.rpc_url):
we should check based on chainId.
Maybe somebody is running their own node and then url is not a match

2023-08-01 10:20 UTC, alexcos20 commented
Mainnet Chain ID:    Hex: 0x5afe,Decimal: 23294
Testnet   Chain ID:    Hex: 0x5aff,Decimal: 23295

2023-08-01 10:39 UTC, trizin commented on pdr_utils/contract.py
> +            if is_sapphire_rpc(self.config.rpc_url):
I fixed it. Thanks!

2023-08-01 11:09 UTC, alexcos20 approved these changes

2023-08-01 14:39 UTC, merged